### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by lutoma**
Adding a set of thinking emoji variations. Two sets of those already exists, but I've added this one mostly for the one animated sticker.

### CODE REVIEW

**Comment by darkobits** [comment]
@romainricard Would like to get your thoughts here as I know you are trying to avoid duplicates. Should we just do a merge of all the related packs?

**Comment by lutoma** [comment]
If someone wants to go through the effort of merging the three sticker packs, I'm totally up for that too.

**Comment by romainricard** [comment]
Yep, merging this pack could be great! I'll leave this PR open, and I'll do the merge this week if it's OK for everybody.

**Comment by darkobits** [comment]
@all-contributors add @lutoma for content

**Comment by romainricard** [comment]
I gave it a try, but stickers de-duplication is a nightmare in packs where every emoji is :thinking: . I'll merge this PR; if someone from the future feels like trying, please do!

Thanks again @lutoma !

**Pull request closed without merging**
