### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by mnxmna**
f71ea6dc2386bb50494f3e3e6bd6c829:
  key: 3d9faca977c20e088be06768b2d08c5f9495c11f3c4fb609f84fa775ffba1d21
  source: Maxccm
  tags:
    - outofdark
    - funny
    - laugh
    - ghost
    - stephenchow

### CODE REVIEW

**Comment by lightlifephotography** [comment]
b9187f45e7dc0026a41c620c25088754:
  key: 5363bc845316a0e3ff37ea5c98cd9c211f1506420bb6c41da53cf2322bdd1603
  source: 'https://t.me/addstickers/FlameHeadGirl'
  tags:
    - Female
    - White
    - red hair
    - hottie
    - fun
    - person
    - diva
    - women
    - lady
    - long hair
    - lifestyle

**Comment by lightlifephotography** [comment]
I really can' figure out how to edit this stickers.yml any help?

**Comment by mnxmna** [comment]
@all-contributors
@fluffykins

**Comment by mnxmna** [comment]
@all-contributors add @fluffykins for content

**Pull request closed without merging**
