### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by arkozfik**
Create a new branch for this

21

# commit and start a pull request

### CODE REVIEW

**Comment by arkozfik** [comment]
First time doing this, sorry if i messed it up! Thanks for this amazing project!

**Comment by romainricard** [comment]
Everything's fine, thanks!

**Comment by arkozfik** [comment]
Hey romainricard, I'm just wondering. Who would i need to contact in case I want to remove a sticker pack i created from Signal Stickers?

**Comment by romainricard** [comment]
You can open an Issue on this repo asking for removal !

**Pull request closed without merging**
