### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by telecasticsushi**
Hi. I added the stickers from the [signal subreddit](https://www.reddit.com/r/signal/comments/kv2j40/heres_a_bunch_of_stickers_i_imported_from_line_to/) to your site. There's a lot of stickers to add if you don't mind. This is my first time using Github. I hope I do it correctly.

### CODE REVIEW

**Comment by romainricard** [comment]
It seems that there is a lot of packs that already exists on `signalstickers.com`. Could you please check all your packs and search the title on the site? Thank you very much! :+1:

**Comment by telecasticsushi** [comment]
Hi. I checked it again and the only duplicate I can find is the Stitch. I can assure to you that there is no duplicate. There might be sticker pack with similar name but they contains different set of stickers. How do I proceed? This is my first time using Github.

**Review by prabou — APPROVED** [review]

**Comment by romainricard** [comment]
Stitch (existing pack has more stickers) and One punch man were duplicated.
Thanks, the rest will be merged!

**Comment by romainricard** [comment]
@all-contributors please add @telecasticsushi for content

**Pull request closed without merging**
